import type { TemplateNode } from '../types/index.js';

export interface BuiltinTemplate {
  name: string;
  genre: string;
  description: string;
  structure: TemplateNode[];
}

export const BUILTIN_TEMPLATES: BuiltinTemplate[] = [
  {
    name: '玄幻经典',
    genre: '玄幻',
    description: '经典玄幻小说三幕结构：崛起、争霸、巅峰',
    structure: [
      { title: '第一卷：凡人崛起', level: 0 },
      { title: '少年出身与家族', content: '主角身世、家族背景、天赋测试', level: 1 },
      { title: '机缘初遇', content: '意外获得奇遇/宝物/传承', level: 1 },
      { title: '初入修炼', content: '修炼体系介绍、第一次突破', level: 1 },
      { title: '宗门历练', content: '拜入宗门、结识同伴、初露锋芒', level: 1 },
      { title: '第二卷：风云际会', level: 0 },
      { title: '秘境探险', content: '进入秘境/遗迹，获得重要资源', level: 1 },
      { title: '宗门大比', content: '参加比武/排位赛，展现实力', level: 1 },
      { title: '势力冲突', content: '卷入宗门/家族/帝国的矛盾', level: 1 },
      { title: '生死危机', content: '遭遇强敌或阴谋，面临生死考验', level: 1 },
      { title: '第三卷：登临巅峰', level: 0 },
      { title: '破茧重生', content: '绝境突破，实力大增', level: 1 },
      { title: '清算恩怨', content: '逐一击败对手，了结因果', level: 1 },
      { title: '终极之战', content: '与最终Boss决战', level: 1 },
      { title: '新世界开启', content: '突破桎梏，飞升/踏入更高层次', level: 1 },
    ],
  },
  {
    name: '都市逆袭',
    genre: '都市',
    description: '都市爽文经典路线：低谷、逆袭、登顶',
    structure: [
      { title: '第一阶段：低谷', level: 0 },
      { title: '落魄现状', content: '主角遭遇人生低谷，被人轻视', level: 1 },
      { title: '转折契机', content: '获得金手指/系统/神秘能力', level: 1 },
      { title: '初试身手', content: '小试牛刀，引起关注', level: 1 },
      { title: '第二阶段：崛起', level: 0 },
      { title: '事业起步', content: '利用能力创业/投资/提升', level: 1 },
      { title: '贵人相助', content: '遇到关键人物，获得支持', level: 1 },
      { title: '初次打脸', content: '回击曾经看不起自己的人', level: 1 },
      { title: '感情发展', content: '与女主角感情升温', level: 1 },
      { title: '第三阶段：登顶', level: 0 },
      { title: '商业帝国', content: '事业做大做强', level: 1 },
      { title: '终极对决', content: '与最大对手正面交锋', level: 1 },
      { title: '功成名就', content: '站在巅峰，回首来路', level: 1 },
    ],
  },
  {
    name: '仙侠问道',
    genre: '仙侠',
    description: '修仙问道：从凡人到飞升的完整历程',
    structure: [
      { title: '第一卷：凡尘入道', level: 0 },
      { title: '凡俗世界', content: '主角的凡人生活和入道因缘', level: 1 },
      { title: '拜入仙门', content: '进入修仙宗门，开始修炼', level: 1 },
      { title: '筑基练气', content: '初级修炼阶段，基础功法', level: 1 },
      { title: '仙门试炼', content: '参加宗门考核和历练', level: 1 },
      { title: '第二卷：道心渐成', level: 0 },
      { title: '结丹元婴', content: '修为突破，实力大增', level: 1 },
      { title: '道侣之缘', content: '遇到命定之人，情感纠葛', level: 1 },
      { title: '天劫降临', content: '渡劫飞升的前兆和考验', level: 1 },
      { title: '正邪大战', content: '正道与魔道的冲突升级', level: 1 },
      { title: '第三卷：飞升之路', level: 0 },
      { title: '证道突破', content: '领悟大道，修为圆满', level: 1 },
      { title: '终局之战', content: '与宿敌的最终对决', level: 1 },
      { title: '飞升仙界', content: '超脱凡尘，踏入仙界', level: 1 },
    ],
  },
  {
    name: '甜宠言情',
    genre: '言情',
    description: '经典甜宠言情：相遇、试探、相爱',
    structure: [
      { title: '第一幕：命运相遇', level: 0 },
      { title: '初次邂逅', content: '男女主角意外相遇，留下印象', level: 1 },
      { title: '再次相遇', content: '因工作/生活原因被迫接触', level: 1 },
      { title: '矛盾冲突', content: '性格/立场冲突，互相看不顺眼', level: 1 },
      { title: '第二幕：渐生情愫', level: 0 },
      { title: '意外亲近', content: '被迫/意外共处，发现对方优点', level: 1 },
      { title: '暗生好感', content: '开始在意对方，小鹿乱撞', level: 1 },
      { title: '误会波折', content: '第三者/误会/家族因素制造障碍', level: 1 },
      { title: '明确心意', content: '经历波折后确认感情', level: 1 },
      { title: '第三幕：甜蜜相守', level: 0 },
      { title: '公开恋情', content: '面对外界阻力，坚定在一起', level: 1 },
      { title: '共同成长', content: '互相支持，一起面对挑战', level: 1 },
      { title: '圆满结局', content: '修成正果，甜蜜日常', level: 1 },
    ],
  },
  {
    name: '科幻末世',
    genre: '科幻',
    description: '科幻末世题材：危机、求生、重建',
    structure: [
      { title: '第一幕：末日降临', level: 0 },
      { title: '世界设定', content: '建立末世背景和规则体系', level: 1 },
      { title: '灾难爆发', content: '末日事件发生，社会秩序崩塌', level: 1 },
      { title: '艰难求生', content: '主角初期生存挑战', level: 1 },
      { title: '获得能力', content: '觉醒异能/发现科技/得到装备', level: 1 },
      { title: '第二幕：势力崛起', level: 0 },
      { title: '建立基地', content: '找到据点，组建团队', level: 1 },
      { title: '资源争夺', content: '与其他幸存者势力竞争', level: 1 },
      { title: '末世真相', content: '发现灾难背后的真相', level: 1 },
      { title: '第三幕：希望之光', level: 0 },
      { title: '反攻计划', content: '制定拯救/重建方案', level: 1 },
      { title: '最终决战', content: '与灾难源头/反派势力决战', level: 1 },
      { title: '重建文明', content: '废墟上重建希望', level: 1 },
    ],
  },
  {
    name: '悬疑推理',
    genre: '悬疑',
    description: '悬疑推理经典结构：案件、调查、真相',
    structure: [
      { title: '第一幕：迷局开启', level: 0 },
      { title: '案件发生', content: '离奇案件/事件引发故事', level: 1 },
      { title: '主角登场', content: '侦探/调查者介入', level: 1 },
      { title: '初步调查', content: '收集线索，初步分析', level: 1 },
      { title: '嫌疑人登场', content: '各具嫌疑的人物出现', level: 1 },
      { title: '第二幕：层层迷雾', level: 0 },
      { title: '线索交织', content: '多条线索并行，互相矛盾', level: 1 },
      { title: '误导性线索', content: '精心设计的红鲱鱼', level: 1 },
      { title: '第二起案件', content: '案件升级或出现新受害者', level: 1 },
      { title: '调查困境', content: '陷入僵局，看似无解', level: 1 },
      { title: '第三幕：真相大白', level: 0 },
      { title: '关键突破', content: '发现决定性线索或证据', level: 1 },
      { title: '真相揭露', content: '推理链条完整，揭示真凶', level: 1 },
      { title: '尾声', content: '案件收尾，人性反思', level: 1 },
    ],
  },
];
